package mathlify

// ── Token types ──────────────────────────────────────────────────────────

case class AMSym(
    input: String,
    output: String,
    tag: String,
    ttype: TType,
    func: Boolean = false,
    acc: Boolean = false,
    rewriteleftright: Option[(String, String)] = None,
    invisible: Boolean = false
)

// ── Symbol table ─────────────────────────────────────────────────────────

val rawSymbols: List[AMSym] = List(
  // Greek letters
  AMSym("alpha", "α", "mi", CONST),
  AMSym("beta", "β", "mi", CONST),
  AMSym("chi", "χ", "mi", CONST),
  AMSym("delta", "δ", "mi", CONST),
  AMSym("Delta", "Δ", "mo", CONST),
  AMSym("epsi", "ε", "mi", CONST),
  AMSym("epsilon", "ε", "mi", CONST),
  AMSym("varepsilon", "ɛ", "mi", CONST),
  AMSym("eta", "η", "mi", CONST),
  AMSym("gamma", "γ", "mi", CONST),
  AMSym("Gamma", "Γ", "mo", CONST),
  AMSym("iota", "ι", "mi", CONST),
  AMSym("kappa", "κ", "mi", CONST),
  AMSym("lambda", "λ", "mi", CONST),
  AMSym("Lambda", "Λ", "mo", CONST),
  AMSym("lamda", "λ", "mi", CONST),
  AMSym("Lamda", "Λ", "mo", CONST),
  AMSym("mu", "μ", "mi", CONST),
  AMSym("nu", "ν", "mi", CONST),
  AMSym("omega", "ω", "mi", CONST),
  AMSym("Omega", "Ω", "mo", CONST),
  AMSym("phi", "ϕ", "mi", CONST),
  AMSym("varphi", "φ", "mi", CONST),
  AMSym("Phi", "Φ", "mo", CONST),
  AMSym("pi", "π", "mi", CONST),
  AMSym("Pi", "Π", "mo", CONST),
  AMSym("psi", "ψ", "mi", CONST),
  AMSym("Psi", "Ψ", "mi", CONST),
  AMSym("rho", "ρ", "mi", CONST),
  AMSym("sigma", "σ", "mi", CONST),
  AMSym("Sigma", "Σ", "mo", CONST),
  AMSym("tau", "τ", "mi", CONST),
  AMSym("theta", "θ", "mi", CONST),
  AMSym("vartheta", "ϑ", "mi", CONST),
  AMSym("Theta", "Θ", "mo", CONST),
  AMSym("upsilon", "υ", "mi", CONST),
  AMSym("xi", "ξ", "mi", CONST),
  AMSym("Xi", "Ξ", "mo", CONST),
  AMSym("zeta", "ζ", "mi", CONST),
  // Binary operations
  AMSym("***", "⋆", "mo", CONST),
  AMSym("**", "∗", "mo", CONST),
  AMSym("*", "⋅", "mo", CONST),
  AMSym("//", "/", "mo", CONST),
  AMSym("\\\\", "\\", "mo", CONST),
  AMSym("setminus", "\\", "mo", CONST),
  AMSym("xx", "×", "mo", CONST),
  AMSym("|><|", "⋈", "mo", CONST),
  AMSym("|><", "⋉", "mo", CONST),
  AMSym("><|", "⋊", "mo", CONST),
  AMSym("-:", "÷", "mo", CONST),
  AMSym("divide", "-:", "mo", DEFINITION),
  AMSym("@", "∘", "mo", CONST),
  AMSym("oplus", "⊕", "mo", CONST),
  AMSym("o+", "⊕", "mo", CONST),
  AMSym("ominus", "⊖", "mo", CONST),
  AMSym("o-", "⊖", "mo", CONST),
  AMSym("otimes", "⊗", "mo", CONST),
  AMSym("ox", "⊗", "mo", CONST),
  AMSym("odot", "⊙", "mo", CONST),
  AMSym("o.", "⊙", "mo", CONST),
  AMSym("sum", "∑", "mo", UNDEROVER),
  AMSym("prod", "∏", "mo", UNDEROVER),
  AMSym("^^^", "⋀", "mo", UNDEROVER),
  AMSym("^^", "∧", "mo", CONST),
  AMSym("vvv", "⋁", "mo", UNDEROVER),
  AMSym("vv", "∨", "mo", CONST),
  AMSym("nnn", "⋂", "mo", UNDEROVER),
  AMSym("nn", "∩", "mo", CONST),
  AMSym("uuu", "⋃", "mo", UNDEROVER),
  AMSym("uu", "∪", "mo", CONST),
  AMSym("dagger", "†", "mo", CONST),
  AMSym("dag", "†", "mo", CONST),
  AMSym("ddagger", "‡", "mo", CONST),
  AMSym("ddag", "‡", "mo", CONST),
  // Binary relations
  AMSym("!=", "≠", "mo", CONST),
  AMSym("ne", "≠", "mo", CONST),
  AMSym(":=", ":=", "mo", CONST),
  AMSym("lt", "<", "mo", CONST),
  AMSym("leq", "≤", "mo", CONST),
  AMSym("le", "≤", "mo", CONST),
  AMSym("lt=", "≤", "mo", CONST),
  AMSym("<=", "≤", "mo", CONST),
  AMSym("gt", ">", "mo", CONST),
  AMSym("geq", "≥", "mo", CONST),
  AMSym("ge", "≥", "mo", CONST),
  AMSym("gt=", "≥", "mo", CONST),
  AMSym(">=", "≥", "mo", CONST),
  AMSym("mlt", "≪", "mo", CONST),
  AMSym("mgt", "≫", "mo", CONST),
  AMSym("-lt", "≺", "mo", CONST),
  AMSym("-<=", "⪯", "mo", CONST),
  AMSym("preceq", "⪯", "mo", CONST),
  AMSym("-<", "≺", "mo", CONST),
  AMSym("prec", "≺", "mo", CONST),
  AMSym(">-=", "⪰", "mo", CONST),
  AMSym("succeq", "⪰", "mo", CONST),
  AMSym(">-", "≻", "mo", CONST),
  AMSym("succ", "≻", "mo", CONST),
  AMSym("!in", "∉", "mo", CONST),
  AMSym("notin", "∉", "mo", CONST),
  AMSym("in", "∈", "mo", CONST),
  AMSym("!sub", "⊄", "mo", CONST),
  AMSym("notsubset", "!sub", "mo", DEFINITION),
  AMSym("subset", "⊂", "mo", CONST),
  AMSym("sub", "⊂", "mo", CONST),
  AMSym("!sup", "⊅", "mo", CONST),
  AMSym("notsupset", "!sup", "mo", DEFINITION),
  AMSym("supset", "⊃", "mo", CONST),
  AMSym("sup", "⊃", "mo", CONST),
  AMSym("!sube", "⊈", "mo", CONST),
  AMSym("notsubseteq", "!sube", "mo", DEFINITION),
  AMSym("subseteq", "⊆", "mo", CONST),
  AMSym("sube", "⊆", "mo", CONST),
  AMSym("!supe", "⊉", "mo", CONST),
  AMSym("notsupseteq", "!supe", "mo", DEFINITION),
  AMSym("supseteq", "⊇", "mo", CONST),
  AMSym("supe", "⊇", "mo", CONST),
  AMSym("!-=", "≢", "mo", CONST),
  AMSym("notequiv", "!-=", "mo", DEFINITION),
  AMSym("-=", "≡", "mo", CONST),
  AMSym("equiv", "≡", "mo", CONST),
  AMSym("~=", "≅", "mo", CONST),
  AMSym("cong", "≅", "mo", CONST),
  AMSym("~~", "≈", "mo", CONST),
  AMSym("approx", "≈", "mo", CONST),
  AMSym("~", "∼", "mo", CONST),
  AMSym("sim", "∼", "mo", CONST),
  AMSym("propto", "∝", "mo", CONST),
  AMSym("prop", "∝", "mo", CONST),
  // Logical
  AMSym("and", "and", "mtext", SPACE),
  AMSym("or", "or", "mtext", SPACE),
  AMSym("not", "¬", "mo", CONST),
  AMSym("neg", "¬", "mo", CONST),
  AMSym("implies", "⇒", "mo", CONST),
  AMSym("=>", "⇒", "mo", CONST),
  AMSym("if", "if", "mo", SPACE),
  AMSym("iff", "⇔", "mo", CONST),
  AMSym("<=>", "⇔", "mo", CONST),
  AMSym("forall", "∀", "mo", CONST),
  AMSym("AA", "∀", "mo", CONST),
  AMSym("exists", "∃", "mo", CONST),
  AMSym("EE", "∃", "mo", CONST),
  AMSym("_|_", "⊥", "mo", CONST),
  AMSym("bot", "⊥", "mo", CONST),
  AMSym("TT", "⊤", "mo", CONST),
  AMSym("top", "⊤", "mo", CONST),
  AMSym("|--", "⊢", "mo", CONST),
  AMSym("vdash", "⊢", "mo", CONST),
  AMSym("|==", "⊨", "mo", CONST),
  AMSym("models", "⊨", "mo", CONST),
  // Grouping brackets
  AMSym("(:", "〈", "mo", LEFTBRACKET),
  AMSym(":)", "〉", "mo", RIGHTBRACKET),
  AMSym("<<", "〈", "mo", LEFTBRACKET),
  AMSym(">>", "〉", "mo", RIGHTBRACKET),
  AMSym("{:", "{:", "mo", LEFTBRACKET, invisible = true),
  AMSym(":}", ":}", "mo", RIGHTBRACKET, invisible = true),
  AMSym("(", "(", "mo", LEFTBRACKET),
  AMSym(")", ")", "mo", RIGHTBRACKET),
  AMSym("[", "[", "mo", LEFTBRACKET),
  AMSym("]", "]", "mo", RIGHTBRACKET),
  AMSym("{", "{", "mo", LEFTBRACKET),
  AMSym("}", "}", "mo", RIGHTBRACKET),
  AMSym("|", "∣", "mo", LEFTRIGHT),
  // Miscellaneous
  AMSym("oint", "∮", "mo", CONST),
  AMSym("int", "∫", "mo", CONST),
  AMSym("partial", "∂", "mo", CONST),
  AMSym("del", "∂", "mo", CONST),
  AMSym("nabla", "∇", "mo", CONST),
  AMSym("grad", "∇", "mo", CONST),
  AMSym("pm", "±", "mo", CONST),
  AMSym("+-", "±", "mo", CONST),
  AMSym("mp", "∓", "mo", CONST),
  AMSym("-+", "∓", "mo", CONST),
  AMSym("emptyset", "∅", "mo", CONST),
  AMSym("O/", "∅", "mo", CONST),
  AMSym("infty", "∞", "mo", CONST),
  AMSym("oo", "∞", "mo", CONST),
  AMSym("aleph", "ℵ", "mo", CONST),
  AMSym("ldots", "...", "mo", CONST),
  AMSym("...", "...", "mo", CONST),
  AMSym("therefore", "∴", "mo", CONST),
  AMSym(":.", "∴", "mo", CONST),
  AMSym("because", "∵", "mo", CONST),
  AMSym(":'", "∵", "mo", CONST),
  AMSym("angle", "∠", "mo", CONST),
  AMSym("/_", "∠", "mo", CONST),
  AMSym("triangle", "△", "mo", CONST),
  AMSym("/_\\", "△", "mo", CONST),
  AMSym("prime", "′", "mo", CONST),
  AMSym("'", "′", "mo", CONST),
  AMSym("\\ ", "\u00A0", "mo", CONST),
  AMSym("frown", "⌢", "mo", CONST),
  AMSym("qquad", "\u00A0\u00A0\u00A0\u00A0", "mo", CONST),
  AMSym("quad", "\u00A0\u00A0", "mo", CONST),
  AMSym("cdots", "⋯", "mo", CONST),
  AMSym("vdots", "⋮", "mo", CONST),
  AMSym("ddots", "⋱", "mo", CONST),
  AMSym("diamond", "⋄", "mo", CONST),
  AMSym("square", "□", "mo", CONST),
  AMSym("lfloor", "⌊", "mo", CONST),
  AMSym("|__", "⌊", "mo", CONST),
  AMSym("rfloor", "⌋", "mo", CONST),
  AMSym("__|", "⌋", "mo", CONST),
  AMSym("lceiling", "⌈", "mo", CONST),
  AMSym("|~", "⌈", "mo", CONST),
  AMSym("rceiling", "⌉", "mo", CONST),
  AMSym("~|", "⌉", "mo", CONST),
  AMSym("CC", "ℂ", "mo", CONST),
  AMSym("NN", "ℕ", "mo", CONST),
  AMSym("QQ", "ℚ", "mo", CONST),
  AMSym("RR", "ℝ", "mo", CONST),
  AMSym("ZZ", "ℤ", "mo", CONST),
  AMSym("hbar", "ℏ", "mo", CONST),
  AMSym("f", "f", "mi", UNARY, func = true),
  AMSym("g", "g", "mi", UNARY, func = true),
  // Standard functions
  AMSym("Lim", "Lim", "mo", UNDEROVER),
  AMSym("lim", "lim", "mo", UNDEROVER),
  AMSym("arcsin", "arcsin", "mo", UNARY, func = true),
  AMSym("arccos", "arccos", "mo", UNARY, func = true),
  AMSym("arctan", "arctan", "mo", UNARY, func = true),
  AMSym("arcsec", "arcsec", "mo", UNARY, func = true),
  AMSym("arccsc", "arccsc", "mo", UNARY, func = true),
  AMSym("arccot", "arccot", "mo", UNARY, func = true),
  AMSym("Arcsin", "Arcsin", "mo", UNARY, func = true),
  AMSym("Arccos", "Arccos", "mo", UNARY, func = true),
  AMSym("Arctan", "Arctan", "mo", UNARY, func = true),
  AMSym("sinh", "sinh", "mo", UNARY, func = true),
  AMSym("cosh", "cosh", "mo", UNARY, func = true),
  AMSym("tanh", "tanh", "mo", UNARY, func = true),
  AMSym("coth", "coth", "mo", UNARY, func = true),
  AMSym("sech", "sech", "mo", UNARY, func = true),
  AMSym("csch", "csch", "mo", UNARY, func = true),
  AMSym("Sinh", "Sinh", "mo", UNARY, func = true),
  AMSym("Cosh", "Cosh", "mo", UNARY, func = true),
  AMSym("Tanh", "Tanh", "mo", UNARY, func = true),
  AMSym("sin", "sin", "mo", UNARY, func = true),
  AMSym("cos", "cos", "mo", UNARY, func = true),
  AMSym("tan", "tan", "mo", UNARY, func = true),
  AMSym("cot", "cot", "mo", UNARY, func = true),
  AMSym("sec", "sec", "mo", UNARY, func = true),
  AMSym("csc", "csc", "mo", UNARY, func = true),
  AMSym("Sin", "Sin", "mo", UNARY, func = true),
  AMSym("Cos", "Cos", "mo", UNARY, func = true),
  AMSym("Tan", "Tan", "mo", UNARY, func = true),
  AMSym("Cot", "Cot", "mo", UNARY, func = true),
  AMSym("Sec", "Sec", "mo", UNARY, func = true),
  AMSym("Csc", "Csc", "mo", UNARY, func = true),
  AMSym("exp", "exp", "mo", UNARY, func = true),
  AMSym("log", "log", "mo", UNARY, func = true),
  AMSym("ln", "ln", "mo", UNARY, func = true),
  AMSym("det", "det", "mo", UNARY, func = true),
  AMSym("dim", "dim", "mo", CONST),
  AMSym("mod", "mod", "mo", CONST),
  AMSym("gcd", "gcd", "mo", UNARY, func = true),
  AMSym("lcm", "lcm", "mo", UNARY, func = true),
  AMSym("lub", "lub", "mo", CONST),
  AMSym("glb", "glb", "mo", CONST),
  AMSym("max", "max", "mo", UNDEROVER),
  AMSym("min", "min", "mo", UNDEROVER),
  AMSym("Log", "Log", "mo", UNARY, func = true),
  AMSym("Ln", "Ln", "mo", UNARY, func = true),
  AMSym("abs", "abs", "mo", UNARY, rewriteleftright = Some(("|", "|"))),
  AMSym("Abs", "abs", "mo", UNARY, rewriteleftright = Some(("|", "|"))),
  AMSym("norm", "norm", "mo", UNARY, rewriteleftright = Some(("∥", "∥"))),
  AMSym("floor", "floor", "mo", UNARY, rewriteleftright = Some(("⌊", "⌋"))),
  AMSym("ceil", "ceil", "mo", UNARY, rewriteleftright = Some(("⌈", "⌉"))),
  // Arrows
  AMSym("uparrow", "↑", "mo", CONST),
  AMSym("uarr", "↑", "mo", CONST),
  AMSym("Downarrow", "⇓", "mo", CONST),
  AMSym("downarrow", "↓", "mo", CONST),
  AMSym("dArr", "⇓", "mo", CONST),
  AMSym("darr", "↓", "mo", CONST),
  AMSym("rightarrowtail", "↣", "mo", CONST),
  AMSym("rightarrow", "→", "mo", CONST),
  AMSym("twoheadrightarrowtail", "⤖", "mo", CONST),
  AMSym("twoheadrightarrow", "↠", "mo", CONST),
  AMSym(">->>", "⤖", "mo", CONST),
  AMSym(">->", "↣", "mo", CONST),
  AMSym("->>", "↠", "mo", CONST),
  AMSym("->", "→", "mo", CONST),
  AMSym("to", "→", "mo", CONST),
  AMSym("|->", "↦", "mo", CONST),
  AMSym("mapsto", "↦", "mo", CONST),
  AMSym("Leftarrow", "⇐", "mo", CONST),
  AMSym("leftarrow", "←", "mo", CONST),
  AMSym("lArr", "⇐", "mo", CONST),
  AMSym("larr", "←", "mo", CONST),
  AMSym("Leftrightarrow", "⇔", "mo", CONST),
  AMSym("leftrightarrow", "↔", "mo", CONST),
  AMSym("hArr", "⇔", "mo", CONST),
  AMSym("harr", "↔", "mo", CONST),
  AMSym("Rightarrow", "⇒", "mo", CONST),
  AMSym("rArr", "⇒", "mo", CONST),
  AMSym("rarr", "→", "mo", CONST),
  AMSym("rightleftharpoons", "⇌", "mo", CONST),
  // Commands with arguments
  AMSym("sqrt", "sqrt", "msqrt", UNARY),
  AMSym("root", "root", "mroot", BINARY),
  AMSym("frac", "/", "mfrac", BINARY),
  AMSym("/", "/", "mfrac", INFIX),
  AMSym("stackrel", "stackrel", "mover", BINARY),
  AMSym("overset", "stackrel", "mover", BINARY),
  AMSym("underset", "stackrel", "munder", BINARY),
  AMSym("_", "_", "msub", INFIX),
  AMSym("^", "^", "msup", INFIX),
  AMSym("hat", "^", "mover", UNARY, acc = true),
  AMSym("bar", "¯", "mover", UNARY, acc = true),
  AMSym("overline", "¯", "mover", UNARY, acc = true),
  AMSym("vec", "→", "mover", UNARY, acc = true),
  AMSym("dot", ".", "mover", UNARY, acc = true),
  AMSym("ddot", "..", "mover", UNARY, acc = true),
  AMSym("overparen", "⏜", "mover", UNARY, acc = true),
  AMSym("overarc", "⏜", "mover", UNARY, acc = true),
  AMSym("underline", "\u0332", "munder", UNARY, acc = true),
  AMSym("ul", "\u0332", "munder", UNARY, acc = true),
  AMSym("underbrace", "⏟", "munder", UNARYUNDEROVER, acc = true),
  AMSym("ubrace", "⏟", "munder", UNARYUNDEROVER, acc = true),
  AMSym("overbrace", "⏞", "mover", UNARYUNDEROVER, acc = true),
  AMSym("obrace", "⏞", "mover", UNARYUNDEROVER, acc = true),
  AMSym("tilde", "~", "mover", UNARY, acc = true),
  AMSym("mbox", "mbox", "mtext", TEXTTYPE),
  AMSym("text", "text", "mtext", TEXTTYPE),
  AMSym("color", "", "mstyle", BINARY),
  AMSym("cancel", "cancel", "menclose", UNARY),
  AMSym("mathbf", "bold", "mstyle", UNARY),
  AMSym("bb", "bold", "mstyle", UNARY),
  AMSym("mathsf", "sans-serif", "mstyle", UNARY),
  AMSym("sf", "sans-serif", "mstyle", UNARY),
  AMSym("mathbb", "double-struck", "mstyle", UNARY),
  AMSym("bbb", "double-struck", "mstyle", UNARY),
  AMSym("mathcal", "script", "mstyle", UNARY),
  AMSym("cc", "script", "mstyle", UNARY),
  AMSym("mathtt", "monospace", "mstyle", UNARY),
  AMSym("tt", "monospace", "mstyle", UNARY),
  AMSym("mathfrak", "fraktur", "mstyle", UNARY),
  AMSym("fr", "fraktur", "mstyle", UNARY),
  // dx/dy/dz/dt definitions
  AMSym("dx", "{:d x:}", "mi", DEFINITION),
  AMSym("dy", "{:d y:}", "mi", DEFINITION),
  AMSym("dz", "{:d z:}", "mi", DEFINITION),
  AMSym("dt", "{:d t:}", "mi", DEFINITION)
)
